version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: url-shortener-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AWS_REGION=us-east-1
    networks:
      - url-shortener-network
volumes:
  redis_data:
networks:
  url-shortener-network:
    driver: bridge
